baseURL = "https://perhapslol.github.io/blog/"
languageCode = "zh-CN"
title = "春华夕拾"
theme = "poison"

[params]
  description = "个人博客"
  author = "Perhaps"
  hideToc = false
  highlightJs = true

[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "Notes"
    weight = 3
    url = "/notes/"
  [[menu.main]]
    name = "About"
    weight = 4
    url = "/pages/about/"
  [[menu.main]]
    name = "Guestbook"
    weight = 5
    url = "/pages/guestbook/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true
