baseURL = "https://perhapslol.github.io/blog/"
languageCode = "zh-cn"
title = "春华夕拾"
theme = "poison"

[params]
  author = "Perhaps"
  description = "记录学习历程，分享思考感悟"
  copyright = "© 2024 Perhaps. All rights reserved."
  showToc = true
  hideToc = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
